### ISSUE TITLE
'Commands' is a reserved export and may only be used to export the result of codegenNativeCommands

### ISSUE THREAD

**Issue by jmatsushita** [amjadbouhouch/rn-text-editor#1]
Hi there,

Great to see a project to address the lack of text editor that are not webview based for react-native 👍 

After installing the package, I get the following error:
```
Web Bundling failed 9183ms (platforms/client/index.tsx)
error: ../../node_modules/rn-text-editor/lib/module/core/Extensions/commands.js: .../node_modules/rn-text-editor/lib/module/core/Extensions/commands.js: 'Commands' is a reserved export and may only be used to export the result of codegenNativeCommands.
```

Here's more info about my system (I use expo sdk50, metro web and expo router):
```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - /nix/store/85siw3p53ki5lldcshgah2rrlrcgi527-nodejs-18.19.1/bin/node
      Yarn: 4.0.2 - /nix/store/06c9dy4mcp7c9mvbhajsdsx7bzny6h30-yarn-1.22.21/bin/yarn
      npm: 10.2.4 - /nix/store/85siw3p53ki5lldcshgah2rrlrcgi527-nodejs-18.19.1/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.1 - /nix/store/rkma2q5cc1m4yxhcp2bhf20xbx0hijph-cocoapods-1.15.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0.1/15A507 - /nix/store/k4zhfk321q6rs433hgapwiiimd8drdy2-xcode-wrapper-15.0.1/bin/xcodebuild
    Expo Workflow: bare
```

Cheers,

Jun

**Comment by jmatsushita** [comment]
Running twith `DEBUG='Metro:*'` I get a more detailed stack trace.

I tracked the problem to this code in the `babel-plugin-codegen` https://github.com/facebook/react-native/blob/57ed0fb30931979742634a1faa9a4d3b5261e50d/packages/babel-plugin-codegen/index.js#L115-L158 

This pass is configured by `@expo/metro-config` which is also uses the project's `babel.config.js`. So there might be a way to avoid the `PluginPass.ExportNamedDeclaration` for specific modules as a workaround.

But unless something is misconfigured somewhere, I guess it's unexpected that there are global restrictions for naming exports. I'll submit a question upstream with `expo`.

**Comment by jmatsushita** [comment]
Oh, I see that you've already fixed this https://github.com/amjadbouhouch/rn-text-editor/commit/332fa768b3e4bad2de064e3bb2497fafa81bed22 

I was using the default (`latest`) npm version, using instead `yarn add rn-text-editor@beta` fixed it.

**Comment by amjadbouhouch** [comment]
Hi @jmatsushita, thank you for your interest and for giving it a try!   🙌
I've been busy lately & I was waiting for this patch: https://github.com/facebook/react-native/issues/29063#issuecomment-1925550545  
I've done the basics & while the solution appears straightforward, I'll keep adding more features & fixing some bugs  in the upcoming iterations.

Thanks!
