### ISSUE TITLE
Invalid content for node doc: <>

### ISSUE THREAD

**Issue by IslamRustam** [amjadbouhouch/rn-text-editor#2]
Installed this lib with `npm i` and after I call useEditor hook I get this error:
![simulator_screenshot_0890B8BA-2F42-42CD-8A2C-F9FAF198A8B7](https://github.com/amjadbouhouch/rn-text-editor/assets/71266873/212355bd-0d62-4594-b0d3-deae7cb1b105)

Code looks like this:
```
import { EditorContent, extensions, useEditor } from 'rn-text-editor';
// ...
 const inputRef = React.useRef<TextInput>(null);
    const editor = useEditor({
        enableCoreExtensions: true,
        onUpdate(props) {
            console.log(props.editor.contentAsJson());
        }
    });

    return (
        <EditorContent
            editor={editor}
            placeholder="Write something..."
            inputRef={inputRef}
            autoFocus
        />
    );
// ...
```

Have any ideas about this error and how to fix it?

**Comment by amjadbouhouch** [comment]
Hi @IslamRustam  
Make sure you install the beta version  
```bash
npm i rn-text-editor@0.2.0-beta.3
```
the docs: https://www.npmjs.com/package/rn-text-editor/v/0.2.0-beta.3  
Example: https://github.com/amjadbouhouch/rn-text-editor/tree/v0.2.0-beta.3/example

& It's not stable; there is a lot of work that needs to be done. Due this https://github.com/facebook/react-native/issues/29063#issuecomment-1925550545

**Comment by IslamRustam** [comment]
Using beta version indeed fixed it, but editor itself does require some work. Hopefully you will manage to achieve what you plan to!
